In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('Trial_dataset1_10000_with_GoogleReviews.csv',encoding='latin-1', usecols = [' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings'])
df2 = pd.read_csv('Trial_dataset10001_20000_with_GoogleReviews.csv',encoding='latin-1', usecols = [' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings'])
df3 = pd.read_csv('Trial_dataset22501_25269.csv',encoding='latin-1')

In [3]:
df1.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,Highly Recommended â M-Brothers Automotive B...,5 | 5 | 5 | 5 | 5
1,SC402065,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5
2,SC444940,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5
3,SC857241,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4
4,11215147,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5

In [4]:
df2.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,12839866,3.9,NaN,Whilst I respect and understand that Iâm lea...,1 | 5 | 5 | 5 | 1
1,16555427,4.0,NaN,My family orders from here at least once a mon...,2 | 2 | 5 | 5 | 5
2,12901062,NaN,NaN,NaN,NaN
3,NI680239,4.2,NaN,I tested the doner kebab in naan bread with sa...,4 | 5 | 5 | 5 | 1
4,15816064,4.0,NaN,Weâre regular customers here but the last 2 ...,2 | 5 | 1 | 5 | 5

In [5]:
df3.head()

   CompanyNumber              CompanyName RegAddress.PostCode
0       16349234  NARDOS KITCHEN & BAKERY              LS97BG
1       15860923          LA FIESTA LEEDS              LS28BT
2       16403992           RUMBLES WELDON             NN173GY
3       15998193           R AROMA BISTRO              CV11LB
4       16479314             KOYUNCU 1989              N182NA

In [6]:
complete_df = pd.concat([df1,df2],axis=0)

In [7]:
complete_df.isna().sum()

 CompanyNumber                          0
Google_Overall_Rating                4340
Google_Price_Level                  14630
Google_Review_Texts                  4423
Google_Individual_Review_Ratings     4349
dtype: int64

In [8]:
complete_df.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,SC780693,4.7,NaN,Highly Recommended â M-Brothers Automotive B...,5 | 5 | 5 | 5 | 5
1,SC402065,4.2,1.0,Small but friendly establishment. Couple of TV...,5 | 5 | 5 | 1 | 5
2,SC444940,4.6,NaN,The best vegan pizza in Inverclyde! Absolutely...,5 | 5 | 5 | 5 | 5
3,SC857241,4.7,2.0,Food was great! My husband said it was the bes...,4 | 5 | 1 | 4 | 4
4,11215147,4.8,NaN,Best pint of bass I have had in a long time fr...,5 | 5 | 5 | 5 | 5

In [9]:
incomplete_df = complete_df[complete_df['Google_Overall_Rating'].isna()]

In [10]:
incomplete_df

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
12,15581389,NaN,NaN,NaN,NaN
14,7885142,NaN,NaN,NaN,NaN
15,14486927,NaN,NaN,NaN,NaN
17,SC847346,NaN,NaN,NaN,NaN
21,9317797,NaN,NaN,NaN,NaN
...,...,...,...,...,...
9966,16154270,NaN,NaN,NaN,NaN
9980,15971484,NaN,NaN,NaN,NaN
9991,17004630,NaN,NaN,NaN,NaN
9992,9296071,NaN,NaN,NaN,NaN
9994,16188473,NaN,NaN,NaN,NaN

In [11]:
complete_df = pd.concat([complete_df, incomplete_df]).drop_duplicates(keep=False)

In [13]:
complete_df.isna().sum()

 CompanyNumber                          0
Google_Overall_Rating                   0
Google_Price_Level                  10290
Google_Review_Texts                    83
Google_Individual_Review_Ratings        9
dtype: int64

In [12]:
incomplete_df = incomplete_df.drop(['Google_Overall_Rating','Google_Price_Level'],axis=1)

In [13]:
df3 = df3.drop(['CompanyName','RegAddress.PostCode'],axis =1)

In [14]:
incomplete_df.head()

   CompanyNumber
12      15581389
14       7885142
15      14486927
17      SC847346
21       9317797

In [15]:
df3.head()

  CompanyNumber
0      16349234
1      15860923
2      16403992
3      15998193
4      16479314

In [16]:
incomplete_df = pd.concat([df3,incomplete_df]).drop_duplicates(keep=False)

In [17]:
incomplete_df

     CompanyNumber
0         16349234
1         15860923
2         16403992
3         15998193
4         16479314
...            ...
9966      16154270
9980      15971484
9991      17004630
9992       9296071
9994      16188473

[7110 rows x 1 columns]

In [18]:
incomplete_df.to_excel('Quer_file.xlsx',index = False)

In [19]:
complete_df.to_excel('Query_complete.xlsx',index = False)