In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('Trial_dataset20001_22500_with_GoogleReviews.csv', encoding='latin-1', usecols = [' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings'])
df2 = pd.read_excel('Quer_file_output.xlsx', usecols = [' CompanyNumber','Google_Overall_Rating','Google_Price_Level','Google_Review_Texts','Google_Individual_Review_Ratings'])

In [3]:
df1.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,16113446,4.7,NaN,"Dear sir/madam, Just a brief note about your r...",4 | 5 | 5 | 5 | 5
1,15106345,2.5,NaN,Friendly and professional team with excellent ...,5 | 1 | 3 | 1
2,14584272,NaN,NaN,NaN,NaN
3,11826918,3.2,1.0,I don't know what happened to this place. It u...,2 | 5 | 1 | 1 | 5
4,14359046,4.7,NaN,Everything was amazing and the prices were gre...,5 | 4 | 5 | 5 | 4

In [4]:
df2.head()

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
0,16349234,5.0,NaN,The food is incredible and service amazing | ...,5 | 5 | 5 | 5 | 5
1,15860923,4.6,NaN,We had to try La fiesta Leeds after hearing it...,3 | 5 | 5 | 3 | 5
2,16403992,4.4,NaN,"First time eating at Rumbles today, sadly it m...",2 | 4 | 4 | 5 | 5
3,15998193,4.4,NaN,"I visited Royal Aroma in Coventry on Sunday, 2...",5 | 1 | 5 | 1 | 5
4,16479314,4.9,NaN,I recently tried Montagu Fish Bar & Kebab and ...,5 | 5 | 5 | 5 | 1

In [5]:
complete_df = pd.concat([df1,df2],axis=0)

In [6]:
complete_df.isna().sum()

 CompanyNumber                         0
Google_Overall_Rating                928
Google_Price_Level                  6592
Google_Review_Texts                  968
Google_Individual_Review_Ratings     930
dtype: int64

In [7]:
incomplete_df = complete_df[complete_df['Google_Overall_Rating'].isna()]

In [8]:
incomplete_df

,CompanyNumber,Google_Overall_Rating,Google_Price_Level,Google_Review_Texts,Google_Individual_Review_Ratings
2,14584272,NaN,NaN,NaN,NaN
8,16673526,NaN,NaN,NaN,NaN
21,15556160,NaN,NaN,NaN,NaN
24,16950116,NaN,NaN,NaN,NaN
25,16164579,NaN,NaN,NaN,NaN
...,...,...,...,...,...
7074,12808690,NaN,NaN,NaN,NaN
7078,16078639,NaN,NaN,NaN,NaN
7101,9261495,NaN,NaN,NaN,NaN
7103,16998258,NaN,NaN,NaN,NaN
7105,16154270,NaN,NaN,NaN,NaN

In [9]:
complete_df = pd.concat([complete_df, incomplete_df]).drop_duplicates(keep=False)

In [10]:
#incomplete_df = incomplete_df.drop(['Google_Overall_Rating'],axis=1)

In [11]:
#incomplete_df.to_excel('Quer_file_03_06_26.xlsx',index = False)

In [12]:
complete_df.to_excel('Query_complete_03_06_26.xlsx',index = False)